# Cloud Build configuration for deploying to Cloud Run
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/stock-data-collector:$SHORT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stock-data-collector:$SHORT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'stock-data-collector'
    - '--image'
    - 'gcr.io/$PROJECT_ID/stock-data-collector:$SHORT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - 'asia-northeast1'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '1800'
    - '--max-instances'
    - '1'
    - '--min-instances'
    - '0'
    - '--service-account'
    - 'stock-data-collector@$PROJECT_ID.iam.gserviceaccount.com'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,BIGQUERY_DATASET=stock_data,BIGQUERY_TABLE=daily_stock_prices,BIGQUERY_LOCATION=asia-northeast1,JQUANTS_BASE_URL=https://api.jquants.com/v1,JQUANTS_REFRESH_TOKEN_SECRET=jquants-refresh-token,LOG_LEVEL=INFO,RETRY_MAX_ATTEMPTS=3,TIMEOUT_SECONDS=30,ENVIRONMENT=production'
    - '--no-allow-unauthenticated'

# Substitutions for environment-specific builds
substitutions:
  _ENVIRONMENT: 'prod'

# Build timeout
timeout: '1200s'

# Build logging
options:
  logging: CLOUD_LOGGING_ONLY